//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://ws.bpsj.newfo.fss.com/", ClrNamespace="ws.bpsj.newfo.fss.com")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", ConfigurationName="IFrontGateService")]
public interface IFrontGateService
{
    
    // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.FaultContractAttribute(typeof(ws.bpsj.newfo.fss.com.Exception), Action="", Name="Exception")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getDataResponse getData(getData request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<getDataResponse> getDataAsync(getData request);
    
    // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    executeRequestResponse executeRequest(executeRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<executeRequestResponse> executeRequestAsync(executeRequest request);
    
    // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    sendMessageResponse sendMessage(sendMessage request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<sendMessageResponse> sendMessageAsync(sendMessage request);
    
    // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    executeGetDataResponse executeGetData(executeGetData request);
    
    [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
    System.Threading.Tasks.Task<executeGetDataResponse> executeGetDataAsync(executeGetData request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getData", WrapperNamespace="http://ws.bpsj.newfo.fss.com/", IsWrapped=true)]
public partial class getData
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    public getData()
    {
    }
    
    public getData(string arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getDataResponse", WrapperNamespace="http://ws.bpsj.newfo.fss.com/", IsWrapped=true)]
public partial class getDataResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @return;
    
    public getDataResponse()
    {
    }
    
    public getDataResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="executeRequest", WrapperNamespace="http://ws.bpsj.newfo.fss.com/", IsWrapped=true)]
public partial class executeRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("arg1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] arg1;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("arg2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] arg2;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute("arg3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] arg3;
    
    public executeRequest()
    {
    }
    
    public executeRequest(string arg0, string[] arg1, string[] arg2, string[] arg3)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
        this.arg2 = arg2;
        this.arg3 = arg3;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="executeRequestResponse", WrapperNamespace="http://ws.bpsj.newfo.fss.com/", IsWrapped=true)]
public partial class executeRequestResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @return;
    
    public executeRequestResponse()
    {
    }
    
    public executeRequestResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="sendMessage", WrapperNamespace="http://ws.bpsj.newfo.fss.com/", IsWrapped=true)]
public partial class sendMessage
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    public sendMessage()
    {
    }
    
    public sendMessage(string arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="sendMessageResponse", WrapperNamespace="http://ws.bpsj.newfo.fss.com/", IsWrapped=true)]
public partial class sendMessageResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @return;
    
    public sendMessageResponse()
    {
    }
    
    public sendMessageResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="executeGetData", WrapperNamespace="http://ws.bpsj.newfo.fss.com/", IsWrapped=true)]
public partial class executeGetData
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute("arg1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] arg1;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute("arg2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] arg2;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=3)]
    [System.Xml.Serialization.XmlElementAttribute("arg3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string[] arg3;
    
    public executeGetData()
    {
    }
    
    public executeGetData(string arg0, string[] arg1, string[] arg2, string[] arg3)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
        this.arg2 = arg2;
        this.arg3 = arg3;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="executeGetDataResponse", WrapperNamespace="http://ws.bpsj.newfo.fss.com/", IsWrapped=true)]
public partial class executeGetDataResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.bpsj.newfo.fss.com/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @return;
    
    public executeGetDataResponse()
    {
    }
    
    public executeGetDataResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IFrontGateServiceChannel : IFrontGateService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class FrontGateServiceClient : System.ServiceModel.ClientBase<IFrontGateService>, IFrontGateService
{
    
    public FrontGateServiceClient()
    {
    }
    
    public FrontGateServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public FrontGateServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FrontGateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public FrontGateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getDataResponse IFrontGateService.getData(getData request)
    {
        return base.Channel.getData(request);
    }
    
    public string getData(string arg0)
    {
        getData inValue = new getData();
        inValue.arg0 = arg0;
        getDataResponse retVal = ((IFrontGateService)(this)).getData(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<getDataResponse> IFrontGateService.getDataAsync(getData request)
    {
        return base.Channel.getDataAsync(request);
    }
    
    public System.Threading.Tasks.Task<getDataResponse> getDataAsync(string arg0)
    {
        getData inValue = new getData();
        inValue.arg0 = arg0;
        return ((IFrontGateService)(this)).getDataAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    executeRequestResponse IFrontGateService.executeRequest(executeRequest request)
    {
        return base.Channel.executeRequest(request);
    }
    
    public string executeRequest(string arg0, string[] arg1, string[] arg2, string[] arg3)
    {
        executeRequest inValue = new executeRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        inValue.arg2 = arg2;
        inValue.arg3 = arg3;
        executeRequestResponse retVal = ((IFrontGateService)(this)).executeRequest(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<executeRequestResponse> IFrontGateService.executeRequestAsync(executeRequest request)
    {
        return base.Channel.executeRequestAsync(request);
    }
    
    public System.Threading.Tasks.Task<executeRequestResponse> executeRequestAsync(string arg0, string[] arg1, string[] arg2, string[] arg3)
    {
        executeRequest inValue = new executeRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        inValue.arg2 = arg2;
        inValue.arg3 = arg3;
        return ((IFrontGateService)(this)).executeRequestAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    sendMessageResponse IFrontGateService.sendMessage(sendMessage request)
    {
        return base.Channel.sendMessage(request);
    }
    
    public string sendMessage(string arg0)
    {
        sendMessage inValue = new sendMessage();
        inValue.arg0 = arg0;
        sendMessageResponse retVal = ((IFrontGateService)(this)).sendMessage(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<sendMessageResponse> IFrontGateService.sendMessageAsync(sendMessage request)
    {
        return base.Channel.sendMessageAsync(request);
    }
    
    public System.Threading.Tasks.Task<sendMessageResponse> sendMessageAsync(string arg0)
    {
        sendMessage inValue = new sendMessage();
        inValue.arg0 = arg0;
        return ((IFrontGateService)(this)).sendMessageAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    executeGetDataResponse IFrontGateService.executeGetData(executeGetData request)
    {
        return base.Channel.executeGetData(request);
    }
    
    public string executeGetData(string arg0, string[] arg1, string[] arg2, string[] arg3)
    {
        executeGetData inValue = new executeGetData();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        inValue.arg2 = arg2;
        inValue.arg3 = arg3;
        executeGetDataResponse retVal = ((IFrontGateService)(this)).executeGetData(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<executeGetDataResponse> IFrontGateService.executeGetDataAsync(executeGetData request)
    {
        return base.Channel.executeGetDataAsync(request);
    }
    
    public System.Threading.Tasks.Task<executeGetDataResponse> executeGetDataAsync(string arg0, string[] arg1, string[] arg2, string[] arg3)
    {
        executeGetData inValue = new executeGetData();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        inValue.arg2 = arg2;
        inValue.arg3 = arg3;
        return ((IFrontGateService)(this)).executeGetDataAsync(inValue);
    }
}
namespace ws.bpsj.newfo.fss.com
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class Exception : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("Exception", "http://ws.bpsj.newfo.fss.com/");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
}
